apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-demo1
spec:
  selector:
    matchLabels:
      app: nodejs-demo1
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: nodejs-demo1
    spec:
      containers:
      - name: nodejs-demo1
        image: dando77/demo
        ports:
        - containerPort: 3000
