name: Docker Image CICD_Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository  # ✅ Fetches your repository
      uses: actions/checkout@v4
    
    - name: Get Docker Image Tag
      run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            TAG=${GITHUB_REF#refs/tags/}
          elif [[ $GITHUB_REF == refs/heads/main ]]; then
            TAG=latest
          else
            TAG=${GITHUB_SHA::7}
          fi
          echo "TAG=$TAG" >> $GITHUB_ENV
    
      
    - name: Debug Repository Structure
      run: |
          pwd
          ls -la  # Check if Dockerfile exists
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD1 }}
          context: .


    - name: Build Docker Image
      run: |
          docker build -t dando1/node:$TAG .
          
      
    - name: Push Docker Image
      run: |
          docker push  dando1/node:$TAG
