name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD1 }}
          context: .


    - name: Build Docker Image
      run: |
          docker build -t dando1/node:100 .
          
      
    - name: Push Docker Image
      run: |
          docker push tag dando1/node:100
